// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using api.Models;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230301010026_ChangeCasingConvention-UpdateUserAddGoogleAccessToken-NewTableUserJunctions")]
    partial class ChangeCasingConventionUpdateUserAddGoogleAccessTokenNewTableUserJunctions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("api.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("gAccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("gAccessToken")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("api.UserJunctions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<int>("firstUserId")
                        .HasColumnType("integer");

                    b.Property<int>("secondUserId")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("firstUserId");

                    b.HasIndex("secondUserId");

                    b.ToTable("UserJunctions");
                });

            modelBuilder.Entity("api.UserJunctions", b =>
                {
                    b.HasOne("api.User", "firstUser")
                        .WithMany()
                        .HasForeignKey("firstUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("api.User", "secondUser")
                        .WithMany()
                        .HasForeignKey("secondUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("firstUser");

                    b.Navigation("secondUser");
                });
#pragma warning restore 612, 618
        }
    }
}
